In [1]:
import numpy as np

In [2]:
np.__version__         # __는 내장변수를 뜻하는 것임.

'1.19.5'

In [84]:
def onhotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder = np.array([0,0,0,1,0])
  else: # 8
    cylinder = np.array([0,0,0,0,1]) 
  return cylinder

In [85]:
displacement = 307.9
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1

## if cylinders = 8, origin = 1 ---> onehot encoding
import numpy as np

X_continues = np.array([displacement, horsepower, weight, accel])
# cylinder = np.array([0,0,0,0,1])  # 8
cylinder = onhotcylinder(cylinders)
org = np.array([1,0,0])  # 1

In [86]:
onhotcylinder(4), onhotcylinder(6)

(array([0, 1, 0, 0, 0]), array([0, 0, 0, 1, 0]))

In [87]:
cylinder

array([0, 0, 0, 0, 1])

In [88]:
type(X_continues), type(cylinder), type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

numpy.concatenate : numpy 배열들을 하나로 합치는데 이용         api에서 예제를 사용해볼 것   
np.concatenate((a, b), axis=None)

In [89]:
result = np.concatenate((X_continues, cylinder, org), axis=None)                    
result.shape, result

((12,),
 array([3.079e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

e : 승수를 뜻함  +02 는 *100, +03은 *1000, +01은 *10을 뜻함

[307.0, 130.0, 3504.0, 12.0, 0,0,0,0,1,1,0,0 ] 과 같음
행열의 구조로 넣어주어야 함. (1,12)형태로... 그래서 reshape을 쓴다. 

In [90]:
 result.reshape(1,12), result.size

(array([[3.079e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 12)

result = reshape(-1, result.size) 도 같은 결과를 가져올 수 있다. (소프트코딩 방법) <br> -1은 자기 연산을 뜻함.

In [91]:
result

array([3.079e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00])

# function 이해

In [23]:
# function은 공통적인 것을 묶는 것 --> 반복적인 작업의 기능화

In [24]:
21 + 14

35

In [25]:
32 + 45

77

In [48]:
def sum():
  first = 32
  second = 45
  result = first + second
  return result

In [62]:
def sum(f,s):      # 함수의 외부에선 순서가 중요하고 내부에서는 이름이 중요하다. 
  first = s
  second = f
  result = first + second
  return result, first, second

In [63]:
sum(4,5), sum(3,2), sum(21,564)

((9, 5, 4), (5, 2, 3), (585, 564, 21))

In [67]:
r01,r02,r03 = sum(23, 2)
print(r01,r02)

25 2


In [56]:
21 * 32 * 2

1344

In [57]:
31 * 63 * 41

80073

In [58]:
def multi(x,y,z):
  result = x * y * z
  return result

In [59]:
multi(21,32,2), multi(31,63,41)

(1344, 80073)

In [78]:
# def differenceVars(*var01, **args02)
def diffparam(*var_list, **var_dict):           # 파라미터가 list일 경우 *, dictionary일 경우 **를 쓴다. 요즘 많이 쓰고 있다. 
  print(var_dict)
  result01 = len(var_list)
  return result01

In [79]:
diffparam(1,2,3, a=2,b=3)

{'a': 2, 'b': 3}


3

In [75]:
diffparam(1,2,3,5,6, d=6,a=2,b=3,c=5)

{'d': 6, 'a': 2, 'b': 3, 'c': 5}


5